import Head from "next/head";
import Header from "../components/Header"

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Boom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/boom.png" />
      </Head>
      
      <Header />



    </div>
  );
}
